### ISSUE TITLE
Never ending bolt

### ISSUE THREAD

**Issue by danybenjamin** [Azure-Samples/hdinsight-storm-java-kafka#3]
When I use kafka bolt as specified in this repo, I get a topology that continually processes the same message over and over.

**Configs**
``` # KAFKA Bolt Components
  # Topic selector for KafkaBolt
  - id: "topicSelector"
    className: "org.apache.storm.kafka.bolt.selector.DefaultTopicSelector"
    constructorArgs:
      - "${kafka.bolt.topic}"

  # Mapper for KafkaBolt
  - id: "kafkaMapper"
    className: "org.apache.storm.kafka.bolt.mapper.FieldNameBasedTupleToKafkaMapper"
    constructorArgs:
      - "key"
      - "message"

  # Producer properties for KafkaBolt
  - id: "producerProperties"
    className: "java.util.Properties"
    configMethods:
      - name: "put"
        args:
          - "bootstrap.servers"
          - "${kafka.bolt.hosts}"
      - name: "put"
        args:
          - "acks"
          - "-1"
      - name: "put"
        args:
          - "key.serializer"
          - "org.apache.kafka.common.serialization.StringSerializer"
      - name: "put"
        args:
          - "value.serializer"
          - "org.apache.kafka.common.serialization.StringSerializer"
```

**Bolt**
``` - id: "servcoKafkaQueue"
    className: "org.apache.storm.kafka.bolt.KafkaBolt"
    parallelism: ${KAFKA_BOLT_PARALLELISM}
    configMethods:
    - name: "withProducerProperties"
      args: [ref: "producerProperties"]
    - name: "withTopicSelector"
      args: [ref: "topicSelector"]
    - name: "withTupleToKafkaMapper"
      args: [ref: "kafkaMapper"]
```

**Comment by Blackmist** [comment]
Hi @danybenjamin There are several reasons that might be creating the duplicates, all of them are 'normal' for this example:

1. Storm can provide guarantees around message delivery. However the only way to provide a guarantee of exactly-once processing is to create a topology using the Trident framework. This example doesn't use Trident, so duplicates are possible.

    * https://storm.apache.org/about/guarantees-data-processing.html talks about processing guarantees for Apache Storm.
    * http://storm.apache.org/releases/1.1.0/Trident-tutorial.html talks about the Trident framework.

2. This example uses a spout that randomly generates a sentence, from a list of 5 sentences. When you run this topology on a Storm cluster, it creates multiple instances of this spout across the cluster. I show 8 on my test cluster. So there's a high chance that multiple instances of the spout are going to generate the same message. In a production scenario, you would want to use a spout that provides guarantees around not sending duplicate messages into Storm.

I'll add a work item to add a Trident example to demonstrate exactly once processing.

Please let me know if you have questions on this.

**Comment by danybenjamin** [comment]
This is actually due to some exception happening and the behavior of the catch failing instead of acking: 
```
catch (Exception ex) {
           collector.reportError(ex);
            collector.fail(input);
        }
```

My exception is happening at line 122: ```message = mapper.getMessageFromTuple(input);```
I'm not sure why it's throwing an error with a null message even though there is data in the tuple

**Comment by Blackmist** [comment]
Thanks for the follow up @danybenjamin . I spoke to some folks in HDInsight engineering and they recommend contacting support so they can gather more information on this exception. You can find information on contacting support at https://azure.microsoft.com/support/options/.
